# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!


target 'washu_course_listings' do
    pod 'GoogleMaps'
    pod 'AFNetworking'
    pod 'Alamofire'
    pod 'SwiftyJSON'
end
